
const CHANGE_DIFFICULTY ="CHANGE_DIFFICULTY";
const CHANGE_CATEGORY ="CHANGE_CATEGORY";
const CHANGE_TYPE ="CHANGE_TYPE";
const CHANGE_NUMOFQ ="CHANGE_NUMOFQ";
const CHANGE_SCORE ="CHANGE_SCORE";

export { CHANGE_DIFFICULTY, CHANGE_CATEGORY, CHANGE_TYPE, CHANGE_NUMOFQ, CHANGE_SCORE };



